config/routes.rb
Millap::Application.routes.draw do

  controller :borrower do
    get 'borrower/new', :to => :new, :as => :new
    post 'borrower/create', :to => :create, :as => :create
  end

  controller :fieldpartner do
    get 'fp/new', :to => :new, :as => :new
    post 'fieldpartner/create', :to => :create, :as => :create
  end  

 devise_for :users, :path => "users", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'signup' }, :controllers => { :registrations => "registrations", :confirmations => :confirmations }

devise_for :users do
   get "/signup", :to => "registrations#new" # Add a Custom Route for Registrations
end

  root :to => "home#index"
 
  

  resources :invitations, :only => [:new, :create] do
     collection do
       get :authorize     
       post :get_invitation_token
       get :get_invitation_token
     end	    
   end

   
  controller :home do
    match 'about-milaap', :to => :about, :as => :about
    match 'how-it-works', :to => :how_it_work, :as => :how_it_work
    match 'get-involved', :to => :get_envolved, :as => :get_envolved
    match 'contact-us', :to => :contact_us, :as => :contact_us
    match 'advisory-board', :to => :advisory_board, :as => :advisory_board
    match 'team', :to => :team, :as => :team
    match 'volunteer', :to => :volunteer, :as => :volunteer
    match 'terms', :to => :terms, :as => :terms
    match 'jobs', :to => :jobs, :as => :jobs
    match 'privacy', :to => :privacy, :as => :privacy
    match 'view-all-projects', :to => :view_all_projects, :as => :view_all_projects
    match 'borrower-profile/:id/:name', :to => :borrower_profile, :as => :borrower_profile,:id=>/\d+/,:name=>/.*/
    match 'lender-profile', :to => :lender_profile, :as => :lender_profile
    match 'lend-money-to-borrower', :to => :lend_money_to_borrower, :as => :lend_money_to_borrower
    match 'who-we-are', :to => :who_we_are, :as => :who_we_are
    match 'verify-invitation-code', :to => :verify_invitation_code, :as => :verify_invitation_code
    match 'alpha', :to => :alpha_home, :as => :alpha_home
    match 'thanks', :to => :thank_you, :as => :thank_you
    match 'why-milaap', :to => :why_milaap, :as => :why_milaap
    match 'test', :to => :test, :as => :test
    match 'pledge-a-loan', :to => :pledge, :as => :pledge
    match 'edit-account', :to => :edit_user_account, :as => :edit_user_account
     match 'save-email-info', :to => :save_email_info, :as => :save_email_info
    get 'welcome', :to => :welcome, :as => :welcome
  end

 
  controller :paypal do
    get 'paypal-ipn', :to => :ipn, :as => :ipn
  end 

  controller :pay_tm do
    get 'paytm-ipn', :to => :ipn, :as => :ipn
  end

  controller :admin do
   match 'admin', :to => "Admin::Admin#index", :path => "Admin::Admin#index"
  end 

 controller :twitt_oauth do
    get 'twitter-login', :to => :twitter_login, :as => :twitter_login
    get 'twitter-callback', :to => :twitter_callback, :as => :twitter_callback
  end 

  controller :google_outh do
    get 'google-login', :to => :google_login, :as => :google_login
    get 'google-callback', :to => :google_callback, :as => :google_callback
  end 

 controller :facebook do
    get 'facebook-login', :to => :facebook_login, :as => :facebook_login
    get 'facebook-callback', :to => :facebook_call, :as => :facebook_call
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

#before_filter :check_loan_pledged, :except =>[:index,:save_email_info,:verify_invitation_code,:about,:how_it_work,:get_envolved,:contact_us,:advisory_board,:team,:volunteer,:terms,:jobs,:privacy,:who_we_are,:thank_you,:why_milaap,:pledge, :welcome]
#layout 'alpha', :only=>[:verify_invitation_code]
#layout 'application', :except=>[:verify_invitation_code,:borrower_profile,:view_all_projects,:lend_money_to_borrower,:pledge,:test]
#layout :resolve_layout
 before_filter :authenticate_user!, :only => :welcome

layout  'application'

 def index
    puts "========================================#{request.remote_ip}"
      find_geo_location
    session[:id] = nil
    session[:loan_id] = nil
    session[:amount] = nil
    session[:transaction_fee] = nil
    @title= "MILAAP - Beyond Just Credit"
    session[:tab] = "home"
    sets = ["set1", "set2"]
    @image_path = sets[rand(sets.size)]
    #Rails.logger.info "**************"
    #Rails.logger.info Borrower.find(:all, :limit => 3)
    #Rails.logger.info Borrower.all.limit(3).order_by([:loan_id,:desc])
      @borrowers = Borrower.find(:all, :limit => 3)
 end

 def borrower_profile
  find_geo_location
  @title= "MILAAP - Beyond Just Credit"
  @borrower = Borrower.find(params[:id])
  unless @borrower.blank?
    @loan = Loan.find(@borrower.loan_id)
    @loan_repayments = LoanRepayment.all(:conditions => {:loan_id =>@borrower.loan_id})
    @category = Category.find(@loan.category_id)
    @loan_lenders = LoanLender.all(:conditions => {:loan_id =>@loan.id})
    @loan_funded_percentage = (100 * (@loan.loan_amount_in_dollar - @loan.amount_remaining))/@loan.loan_amount_in_dollar
    @loan_drop_down_values = Loan.find_loan_drop_down_values(@loan,$visiting_user_country)
    #code for google map 
     borrower_address = "#{@borrower.village}" +" "+ "#{@borrower.taluka}"+" "+"#{@borrower.district}"" "+"#{@borrower.state}"" " +"#{@borrower.country}"
     Rails.logger.info "++++++++++++++++++++#{borrower_address}+++++++++++++++++++++++"
     @map = GMap.new("map_div")
     @map.control_init(:large_map => true,:map_type => true)
     results = Geocoding::get("#{borrower_address}") #if results.status == Geocoding::GEO_SUCCESS
     Rails.logger.info "_______#{results}-------------"
     coord = results[0].latlon
     Rails.logger.info "========#{coord}==========="
     @map.center_zoom_init(coord,9)
     @map.overlay_init(GMarker.new(coord,:info_window => "#{borrower_address}"))
  #   render :layout => 'borrower'
  end 
end

	def view_all_projects
		session[:tab] = "pledge"	  
		find_geo_location	 
		@categories = Category.all
		if params[:category]
			@catgry =  Category.first(:conditions => {:name =>params[:category]})
			unless @catgry.blank?
				@loans = Loan.all(:conditions => {:category_id =>@catgry.category_id}).order_by([:loan_id,:desc])
				@loans = @loans.paginate :page => params[:page], :per_page =>5  
				if  @loans.blank?
          flash[:notice] ="We are working on getting loans for the cause that you want to support. It will take us some time. In the meanwhile, you can take a look at other causes and support them."				  
					@loans = Loan.all.order_by([:loan_id,:desc])
				  @loans = @loans.paginate :page => params[:page], :per_page =>5
				end
			else
				@title= "MILAAP - Beyond Just Credit"
				@loans = Loan.all.order_by([:loan_id,:desc])
				@loans = @loans.paginate :page => params[:page], :per_page =>5
			end 
		else
			@title= "MILAAP - Beyond Just Credit"
			@loans = Loan.find(:all, :order => "id desc")
			@loans = @loans.paginate :page => params[:page], :per_page =>5
		end
	end

  
 def lender_profile
  @title= "MILAAP - Beyond Just Credit"
 end

	def lend_money_to_borrower
		 session[:tab] = "pledge"
		 session[:email] = current_user.email
		find_geo_location
		
		@categories = Category.all
		#begin  
			if request.post?
				p "***************"
				p params[:id]
				session[:email] = current_user.email
				session[:id] = params[:id]
    		session[:borrower_id] = params[:borrower_id]
				session[:loan_id] = params[:loan_id]
				session[:amount] = params[:amount_1]  
				@borrower = Borrower.first(:conditions => {:id => params[:id]})
			  @loan = Loan.first(:conditions => {:id =>@borrower.loan_id})
				@category =  Category.first(:conditions => {:id => @loan.category_id})
				@loan_funded_percentage = (100 * (@loan.loan_amount_in_dollar - @loan.amount_remaining))/@loan.loan_amount_in_dollar
				#@loan_funded_percentage = Loan.first(:conditions => {:loan_id =>params[:loan_id]})
				if $visiting_user_country == "India"
					@indian_amt  = params[:amount_1]
				  amt = (params[:amount_1].to_f/45).round(2).ceil
				  @amount = amt  
          @transaction_fee_in_indian_rupees =  ((@indian_amt.to_f*4)/100).round(2)
					session[:indian_amt] = @indian_amt
					@actual_funded_amt = @indian_amt
					
			  else
				  @amount  = params[:amount_1]
					@actual_funded_amt = @amount
				end 
				session[:transaction_fee] = ((@amount.to_f*4)/100).round(2)
			   if $visiting_user_country == "India"
					 @actual_amt = params[:amount_1]
           @drop_down_amt =  params[:amount_1].to_f/45
         else
					 @actual_amt = params[:amount_1]
           @drop_down_amt =  params[:amount_1].to_f
         end 
         @new_loan_funded_percentage = ((100 * (@loan.loan_amount_in_dollar - @drop_down_amt))/@loan.loan_amount_in_dollar).round(2).ceil
	       @actual_new_loan_funded_percentage = 100  - @new_loan_funded_percentage ;
         @actual_new_loan_funded_percentage = @actual_new_loan_funded_percentage.round().ceil
				
				
				
				
			else
				
				@borrower = Borrower.first(:conditions => {:id =>  session[:id]})
				@loan = Loan.first(:conditions => {:loan_id =>session[:loan_id]})
				@category =  Category.first(:conditions => {:category_id => @loan.category_id})
				@loan_funded_percentage = (100 * (@loan.loan_amount_in_dollar - @loan.amount_remaining))/@loan.loan_amount_in_dollar

				#@amount = session[:amount] 
				if $visiting_user_country  =="India"
					@indian_amt  =  session[:amount] 
				  amt = ( session[:amount] .to_f/45).round(2).ceil
				  @amount = amt   
					@transaction_fee_in_indian_rupees =  ((@indian_amt.to_f*4)/100).round(2)
					session[:indian_amt] = @indian_amt
					@actual_funded_amt = @indian_amt
				else
				  @amount  = session[:amount] 
					@actual_funded_amt = @amount
				end 
			  session[:transaction_fee] = ((@amount.to_f*4)/100).round(2)
				 if $visiting_user_country == "India"
           @drop_down_amt =  session[:amount].to_f/45
					 
         else
           @drop_down_amt = session[:amount].to_f
         end 
         @new_loan_funded_percentage = ((100 * (@loan.loan_amount_in_dollar - @drop_down_amt))/@loan.loan_amount_in_dollar).round(2).ceil
	       @actual_new_loan_funded_percentage = 100  - @new_loan_funded_percentage ;
         @actual_new_loan_funded_percentage = @actual_new_loan_funded_percentage.round(2).ceil
				
				
				
				
			 
			end
		#render :layout => 'borrower'
		#rescue
			#redirect_to root_path 
		#end
    end


  def welcome
    @title= "MILAAP - Beyond Just Credit"
  end
 
  def about
    @title= "About MILAAP - Beyond Just Credit"
  end
  
  def contact_us
    @title= "MILAAP - Beyond Just Credit"
  end

  def get_envolved
    @title= "MILAAP - Beyond Just Credit"
    session[:tab] ="get_envolved"
  end

  def how_it_work
    @title= "MILAAP - Beyond Just Credit"
    session[:tab] ="how_it_work" 
  end  
  
  
  def advisory_board
  end  
  
  def team
  end
  
  def volunteer
  end
  
  def terms
  end
  
  def jobs
  end
  
  
  def privacy
  end
  
  def who_we_are
   session[:tab] ="who_we_are"
  end

  def alpha_home
    
  end
  
 def thank_you
 end

 def why_milaap
	 session[:tab] = 'why_milaap'
 end
 
	def pledge
#		session[:tab] = nil
#		if request.post?
#			unless  params[:amount].blank?
#				if  params[:category_choosen] == ""
#					flash[:notice] = "Please choose category."
#				else
#					p "********11----------"
#					if user_signed_in?
#						category = Category.first(:conditions => {:name => params[:category_choosen]})
#						PledgeInfo.create(:user_id=>current_user._id,:email=>current_user.email,:category_id=>category.category_id,:amout=>params[:amount].strip,:currency_type=>params[:amount_currency],:period_type=>params[:amount_period_type],:pledge_id=>"loan_pledged_#{PledgeInfo.all.length+1}")
#						current_user.loan_pledged=true
#						current_user.save!
#						session[:pledged] = true
#						flash[:notice] ="Thank you for the pledge. You can now view the list of entrepreneurs you can support today."
#						redirect_to view_all_projects_path(:category=>category.name)
#					else
#						category = Category.first(:conditions => {:name => params[:category_choosen]})
#						@pledgeinfo = PledgeInfo.create(:category_id=>category.category_id,:amout=>params[:amount].strip,:currency_type=>params[:amount_currency],:period_type=>params[:amount_period_type],:pledge_id=>"loan_pledged_#{PledgeInfo.all.length+1}")
#						session[:pledged] = true
#						flash[:notice] ="Thank you for the pledge. You can now view the list of entrepreneurs you can support today."
#						cookies[:loan_pledged] = {
#							:value => "#{@pledgeinfo.pledge_id}" ,
#							:expires => 30.days.from_now.utc
#						}
#						redirect_to new_user_registration_url
#					end
#				end
#			else
#				flash[:notice] = "Amount can not be blank."
#			end
#		else
#			unless user_signed_in?
#				unless cookies[:loan_pledged].blank?
#					@pledge = PledgeInfo.first(:conditions => {:pledge_id=>cookies[:loan_pledged]})
#					unless @pledge.blank?
#						category = Category.first(:conditions => {:category_id =>@pledge.category_id})
#						p category.name
#						unless @pledge.email.blank?
#							@user = User.first(:conditions => {:email => @pledge.email})
#							unless @user.blank?
#								unless @user.first_name.blank?

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<%= stylesheet_link_tag "static.css"%>

<div class="content">
		<div class="wrapper">
<div id="toppanelbotmborder"></div>
<div id="newsignupmiddlepanel">
  
 <div id="newsignupmiddlecontent">



      <div id="aboutResultcontent">
	    <h2>About Milaap</h2><br/>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor incididunt ut labore et dolore Lorem ipsum dolor sit amet, consectetur adipisicing incididunt ut labore et dolore incididunt ut labore et dolore <a href="#">read more</a> </p>
      </div>
    </div>
  </div>
 </div>
  </div>


app/views/home/alpha_home.html.erb
<% if notice %>
<div id="notification" style="width:900px;text-align:left">
  <p><%= notice.gsub("<br>","<br/>") %></p>
</div>
<% end %>
<% if alert %>
<div id="notification" style="width:900px">
  <p><%= alert %></p>
</div>
<% end %>  
<div class="thankyou-alpha">

 
    <h4>Hello <% if user_signed_in?%><%if !current_user.facebook_name.blank? %>
         <%= current_user.facebook_name.titleize %>
      <% elsif !current_user.email.blank?%>
      <%= current_user.email[0..15] %>
      <% elsif !current_user.twitter_name.blank?%>
      <%= current_user.twitter_name.titleize %>
      <% else %>
      Ananymous
      <% end %><%#= current_user.email %>!<% else %>there<% end %>! Welcome to the alpha version of our platform. Here's what you can do next:</h4>
    <div class="thankyou-alpha-content left">
      <h3><span class="step">1.</span>Browse through our entrepreneurs' profiles</h3>
      <p>You could spare some time to check out <a href="/view-all-projects" style="color:#729DFF">loans</a> spanning across various sectors like education, healthcare, energy, water, sanitation, market linkages to name a few, demanding interventions that go beyond just credit and grant a loan.</p>
      <div class="clear"></div>
    </div>
    <div class="thankyou-alpha-content left" style="margin-right:0px;">
      <h3><span class="step">2.</span>Learn more about Milaap</h3>
      <p>You could check out what Milaap is all about <a href="<%= how_it_work_path %>"  style="color:#729DFF">here</a>, see who are the <a href="<%= who_we_are_path %>"  style="color:#729DFF">people</a> behind it's inception or browse through various profiles <a href="/view-all-projects">here</a> to grant a loan. </p>
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
    <br/>
    <br/>
    <br/>
    <br/>
    


  </div>

app/views/home/edit_user_account.html.erb
<%= stylesheet_link_tag "lender-style.css"%>
<div class="content">
		<div class="wrapper">
		<% if notice %>
		<div id="notification" style="text-align:left;">
			<p><%= notice.gsub("<br>","<br/>") %></p> 
		</div>
	<% end %>
	<% if alert %>
		<div id="notification" style="text-align:left;">
			<p><%= alert %></p>		
		</div>
	<% end %>
		
			<div id="page-heading">
				<h2 class="left">Edit Profile</h2>
				<div class="breadcrumbs right">
					<ul>
						<li><a href="">Home</a><span> &rsaquo;</span></li><li><a href=""> View Entrepreneurs</a><span> &rsaquo;</span></li><li><a href="" class="active"> Entrepreneur's Profile</a><span></span></li>
						<li class="clear"></li>
					</ul>
				</div>
			</div>
			<div class="lenders-details" class="clear"><!-- Lenders' div -->
			
			<form method="post" id="user_new" class="user_new" action="<%= edit_user_account_url %>" accept-charset="UTF-8">
				<div class="info-blurb left"  style="width:680px;"><!-- Lender Info div -->
				
				<div class="left" style="width:200px;">
					<div id="borrower-image" class="left">
						<div class="borrower-image-border">
							<img src="images/lenders/dummy-pic.jpg" alt="Smitabai"/>
						</div>
						<div class="shadow0"></div>
						
					</div>
					<input type="file" name="user[image_url]"/>
					</div>
					<div class="right intro">
						<label class="sub-info">Your First Name</label>
						<input type="text" name="user[first_name]"   id="user_first_name"  value="<%= current_user.first_name unless  current_user.first_name.blank?%>">
						<label class="sub-info">Your Last Name</label>
						<input type="text" name="user[last_name]"   id="user_last_name"  value="<%= current_user.last_name unless  current_user.last_name.blank?%>">
						
						<label class="sub-info">City</label>
					  <input type="text" name="user[city]"   id="user_city"  value="<%= current_user.city unless  current_user.city.blank?%>">	
						<label class="sub-info">Country</label>
						 

					 <%= localized_country_select(:user, :country, [], :include_blank => 'Please choose...') %>
						<label class="sub-info">Brief introduction</label>
						<textarea name="user[intro]"><%= current_user.intro unless  current_user.intro.blank?%></textarea>

						<div class="clear"></div>
						
						<input type="submit" id="submit" value=""/>
					</div>
					<div class="clear"></div>

					<div class="lender-support">
						<h4>Entrepreneurs' supported</h4>
						<div class="borrower-support-info">
							<div class="intro-first">
								<h3 class="left">You haven't supported any entrepreneur as yet</h3>								
								
							</div>
							<div class="clear"></div>
						</div>



						<div class="shadow2"></div>

					</div>
					<div class="shadow1"></div>
				</div><!-- /Lender Info div -->
				</form>
				
				<div class="right sidebar"><!-- Right Sidebar div -->
					<div id="choose-category">
						<h3>Start giving a loan now (choose a category) :</h3>
						<a href=""><img src="images/logo-organic.gif" alt="Organic farming" title="Organic farming" class="left"/></a>
						<a href=""><img src="images/logo-electricity.gif" alt="Electricity" title="Electricity" class="left"/></a>
						<a href=""><img src="images/logo-water.gif" alt="Water" title="Water" class="left"/></a>
						<a href=""><img src="images/logo-trade.gif" alt="Fair trade" title="Fair trade" class="left"/></a>
					</div>
					<div class="repayment-blurb"><!-- Repayment div div -->
						<h3>Loan Details</h3>
						<p>Total amount loaned : Rs. 0</p>
						<p>Total amount repaid : Rs. 0</p>
						<p>Total amount cashed out : Rs. 0</p>
						<p>Milaap credits : 0</p>
					</div><!-- /Repayment div div -->

				</div><!-- /Right Sidebar div -->
				<div class="clear"></div>
				
			</div><!-- /Lenders' div -->
		</div>
	</div>

app/views/home/verify_invitation_code.html.erb
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Milaap-Home</title>
<link rel="icon" href="/images/favicon.ico" type="image/x-icon" />
<%= stylesheet_link_tag "style-alpha.css"%>
<%= stylesheet_link_tag "style.css"%>
<script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE8.js"></script>
<%= javascript_include_tag "jquery-1.3.2.min.js" %><%= javascript_include_tag "jquery-easing-1.3.pack.js" %><%= javascript_include_tag "jquery-easing-compatibility.1.2.pack.js" %><%= javascript_include_tag "jquery-easing-1.3.pack.js" %>
<script type="text/javascript" src="fancybox/jquery.fancybox-1.3.1.js"></script>
<link rel="stylesheet" type="text/css" href="fancybox/jquery.fancybox-1.3.1.css" media="screen" />
<script type="text/javascript">
		$(document).ready(function() {
			$("#signup").fancybox({
				'titlePosition'		: 'inside',
				'transitionIn'		: 'none',
				'transitionOut'		: 'none'
			});

			
			$("#verify").fancybox({
				'titlePosition'		: 'inside',
				'transitionIn'		: 'none',
				'transitionOut'		: 'none'
			});


		});
	</script>



</head>

<body>
<div class="wrapper">
  <!-- Primary nav div -->
  <ul id="primary-nav" class="right">
    <li><a href="/">Home</a></li>
    <li><a href="<%= who_we_are_path %>" title="Who we are" class="<% if  session[:tab] == 'who_we_are'%>active<% else%><% end %>">Who we are</a></li>
    <li><a href="<%= how_it_work_path %>" title="MILAAP - How it works" class="<% if  session[:tab] == 'how_it_work'%>active<% else%><% end %>">How it works</a></li>
    <li><a href="<%= get_envolved_path %>" title="Get involved with MILAAP" class="<% if  session[:tab] == 'get_envolved'%>active<% else%><% end %>">Get involved</a></li>
    <%# if session[:correct_invitation_token] %>
    <% unless current_user.blank? %>
       <li>
      <% if current_user.user_type == "admin" %>
      <a href="/admin/admin">Admin</a>
      <% end%>
    </li>
    <li id="signedin-text"><span> Welcome,
      <%if !current_user.facebook_name.blank? %>
      <%#=  current_user.user_type %> <img src="https://graph.facebook.com/<%= current_user.facebook_uid %>/picture" align="left"/> <%= current_user.facebook_name %>
      <% elsif !current_user.email.blank?%>
      <%= current_user.email[0..15] %>
      <% elsif !current_user.twitter_name.blank?%>
      <%= current_user.twitter_name %>
      <% else %>
      Ananymous
      <% end %>
      |</span><a href="/users/logout">Logout</a> </li>
    <%# else %>
    <!--li id="signup-text"><a id="login"  href="#inline1">Sign in</a></li-->
    <% end %>
    <%# end %>
  </ul>
</div>


<center> 
<br/><br/><br/>
<div class="header clear"><!-- Header div -->
 <div class="wrapper">
  <div id="logo" class="left"><a href="/" title="MILAAP - Beyond Just Credit"><img src="/images/milaap-logo.gif" alt="Milaap"/></a></div>

  <div id="intro-text" class="right">Enabling You &amp; Me to make a sustainable social impact at the bottom of the pyramid</div>
  <div class="clear"></div>
 </div>
</div><!-- /Header div -->

<div id="content"><!-- Content div -->
 <div class="wrapper">  
 <% if notice %>
<div id="notification" style="text-align:left;">
  <p><%= notice.gsub("<br>","<br/>") %></p>
 </div>
<%# notice = nil %>


<% end %>


<% form_tag verify_invitation_code_path do %>
<div id="alpha" style="background:url(images/alpha-bg.png) no-repeat 0 30px; width:970px; height:362px;">
    <div class="alpha-content">
   <p>We have sent you an invite code via email. <br/>Please enter the code to get started.</p>
   <br/><br/>
   <input type="text" class="left" id="enter-invite" onblur="if(this.value == ''){this.value = 'Enter your invite code here';}" onfocus="if(this.value =='Enter your invite code here'){this.value = '';}" onclick="if(this.value =='Enter your invite code here'){this.value = '';}" maxlength="256" value="Enter your invite code here" name="invitation" style="height:33px;"/>
   <input type="submit" value="" style="margin:-4px 0 0 -20px;float:left; background:url(images/enter-site-btn.png) no-repeat 0 0px; border:0px; width:167px; height:43px;"/>
   <p class="clear"></p>  
   <% unless user_signed_in? %> 
     <p id="returning-user"><a id="verify"  href="#inline11">Returning user? Click here to access the site</a></p>
   <% end %>  
   </div>
  </div>
<% end %>

</div>





</div><!-- /Content div -->
<div id="footer"><!-- Footer div -->
 <div class="wrapper">
  <div class="copyright" style="text-align:center">
   <p>&copy; 2010. Milaap.org. All rights reserved.</p>
  </div>
  <div class="clear"></div>
 </div>

</div><!-- /Footer div -->
</center> 
 <div style="display: none;"> <!-- Login blurb-->


 <div id="inline11" style="width:500px;height:320px;overflow:hidden;">
  <form method="post" id="user_new" class="user_new" action="/users/login" accept-charset="UTF-8"> 
  <div id="signup-new">
   <img src="/images/signin_head_img.jpg" alt=""/>
   <div class="signup-left-panel">
    <h4>Sign in with your email</h4>
    <label>Email id</label>
   <input type="text" value=""   id="user_email" name="user[email]" style='border:1px solid #DBD9D8;color:#2F0000;display:block;font-family:"Arial",Helvetica,sans-serif;
font-size:12px;
height:30px;
margin:0px 0;
padding:10px 0 0 10px;
width:200px;
padding:5px;
'>
    <label>Password</label>
        <input type="password" name="user[password]"   id="user[password]"  style='border:1px solid #DBD9D8;color:#2F0000;display:block;font-family:"Arial",Helvetica,sans-serif;
font-size:12px;
height:30px;
margin:0px 0;
padding:10px 0 0 10px;
width:200px;padding:5px;'>
   </div>
   <div class="signup-right-panel">
    <h4>Sign in with another account</h4>
    <%= render :partial=>"/layouts/twitter_google_facebook"%> </div>
   </div>
   <div class="clear"></div> 
   
   <div class="clear"></div>
    <input type="submit" class="modified_submit_signin" value="" style="cursor:pointer"/>
  </div>
</form>
 </div>

</div>


</body>
</html>