config/routes.rb
Millap::Application.routes.draw do

  controller :borrower do
    get 'borrower/new', :to => :new, :as => :new
    post 'borrower/create', :to => :create, :as => :create
  end

  controller :fieldpartner do
    get 'fp/new', :to => :new, :as => :new
    post 'fieldpartner/create', :to => :create, :as => :create
  end  

 devise_for :users, :path => "users", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'signup' }, :controllers => { :registrations => "registrations", :confirmations => :confirmations }

devise_for :users do
   get "/signup", :to => "registrations#new" # Add a Custom Route for Registrations
end

  root :to => "home#index"
 
  

  resources :invitations, :only => [:new, :create] do
     collection do
       get :authorize     
       post :get_invitation_token
       get :get_invitation_token
     end	    
   end

   
  controller :home do
    match 'about-milaap', :to => :about, :as => :about
    match 'how-it-works', :to => :how_it_work, :as => :how_it_work
    match 'get-involved', :to => :get_envolved, :as => :get_envolved
    match 'contact-us', :to => :contact_us, :as => :contact_us
    match 'advisory-board', :to => :advisory_board, :as => :advisory_board
    match 'team', :to => :team, :as => :team
    match 'volunteer', :to => :volunteer, :as => :volunteer
    match 'terms', :to => :terms, :as => :terms
    match 'jobs', :to => :jobs, :as => :jobs
    match 'privacy', :to => :privacy, :as => :privacy
    match 'view-all-projects', :to => :view_all_projects, :as => :view_all_projects
    match 'borrower-profile/:id/:name', :to => :borrower_profile, :as => :borrower_profile,:id=>/\d+/,:name=>/.*/
    match 'lender-profile', :to => :lender_profile, :as => :lender_profile
    match 'lend-money-to-borrower', :to => :lend_money_to_borrower, :as => :lend_money_to_borrower
    match 'who-we-are', :to => :who_we_are, :as => :who_we_are
    match 'verify-invitation-code', :to => :verify_invitation_code, :as => :verify_invitation_code
    match 'alpha', :to => :alpha_home, :as => :alpha_home
    match 'thanks', :to => :thank_you, :as => :thank_you
    match 'why-milaap', :to => :why_milaap, :as => :why_milaap
    match 'test', :to => :test, :as => :test
    match 'pledge-a-loan', :to => :pledge, :as => :pledge
    match 'edit-account', :to => :edit_user_account, :as => :edit_user_account
     match 'save-email-info', :to => :save_email_info, :as => :save_email_info
    get 'welcome', :to => :welcome, :as => :welcome
  end

 
  controller :paypal do
    get 'paypal-ipn', :to => :ipn, :as => :ipn
  end 

  controller :pay_tm do
    get 'paytm-ipn', :to => :ipn, :as => :ipn
  end

  controller :admin do
   match 'admin', :to => "Admin::Admin#index", :path => "Admin::Admin#index"
  end 

 controller :twitt_oauth do
    get 'twitter-login', :to => :twitter_login, :as => :twitter_login
    get 'twitter-callback', :to => :twitter_callback, :as => :twitter_callback
  end 

  controller :google_outh do
    get 'google-login', :to => :google_login, :as => :google_login
    get 'google-callback', :to => :google_callback, :as => :google_callback
  end 

 controller :facebook do
    get 'facebook-login', :to => :facebook_login, :as => :facebook_login
    get 'facebook-callback', :to => :facebook_call, :as => :facebook_call
  end

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
 
    #validate :recipient_is_not_registered
    #validate :sender_has_invitations, :if => :sender
    validates  :first_name, :last_name , :presence => true
    validates  :recipient_email,  :presence => true, :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}  
    
    #before_create :generate_code
    # before_create :decrement_sender_count
    #attr_accessible :recipient_email, :sender, :invitation_token,:sent_at,:first_name,:last_name
   
    private

    def recipient_is_not_registered
        errors.add :recipient_email, 'is already registered' if recipient_email = recipient_email
    end

    def sender_has_invitations
         user = User.where(:invitation_token  => self.invitation_token)
         unless user.invitation_limit > 0
         errors.add_to_base 'You have reached your limit of invitations to send.'
        end
    end
    
      
   def self.generate_code 
     chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
     newpass = ""
     1.upto(7) { |i| newpass << chars[rand(chars.size-1)] }
     return newpass
   end 

end

app/controllers/admin/invitations_controller.rb
class Admin::InvitationsController < ApplicationController
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
   def  authorize
       @invitation = Invitation.new
        respond_to do |format|
           format.html # new.html.erb
           format.xml  { render :xml => @invitation}
        end 
   end
   
   #for getting token from user
   def get_invitation_token
       @invitation = Invitation.where(params[:invitation]).first
        respond_to do |format|
           if !@invitation.blank?
	     @invitation.update_attributes(:invitation_confirm => true)
	     format.html {redirect_to(root_url, :notice => 'You are Authorized !! :)')}
	     format.xml  {render :xml => root_url, :status => :authorized, :location => root_url}
	   else
             format.html{redirect_to(authorize_invitations_url, :notice => 'Invitation Token not match. Sorry :(')}
	     format.xml  { render :xml => authorize_invitations_url }
	   end
        end
    end
    
    def new
       @invitation = Invitation.new
	respond_to do |format|
           format.html 
           format.xml { render :xml => @invitation }
	end
    end
  
    def create
        @invitation = Invitation.new(params[:invitation])
	@invitation.invitation_token = Invitation.generate_code
		
	respond_to do |format|
           if @invitation.save
             if !@invitation.blank? 
               # &&  user_signed_in? 
	        @invitation.update_attributes(:sender => "admin@millap.org", :sent_at => Time.now)
	        p ">>>object>>> saved.."
		p @invitation.inspect
	        MilaapMailer.send_token(@invitation).deliver
               # @user = User.find(current_user._id)
	#	@user.update_attributes!(:invitation_token  =>  @invitation.invitation_token,  :invitation_limit => @user.invitation_limit-1)
		format.html {redirect_to(verify_invitation_code_url, :notice => "Thank you,Invitation Token has been sent to your email address.Please check to get started.")}  	       
		format.xml  {render :xml => root_url, :location => root_url }
	      else
	        format.html {redirect_to(new_user_session_url, :notice => "You need to logged in to send invitaions :)")}  	       
		format.xml  {render :xml => new_user_session_url, :location => new_user_session_url }
	      end
            else
	       format.html {redirect_to(new_invitation_url, :notice => "All fields are compulsory field.")}  	       
	       format.xml  {render :xml => new_invitation_url, :status => :authorized, :location => root_url }
	    end
        end
   end
       
end  
    
    
  

app/helpers/admin/invitations_helper.rb
module Admin::InvitationsHelper
end

app/views/invitations/authorize.html.erb
<div id="toppanelbotmborder"></div>
<div id="newsignupmiddlepanel">
<div id="newsignupmiddlecontent">
 
<%= content_tag(:title, "Enter Invitation Token") %>
<% if  flash[:alerts] %>
  <div id="notification" style="width:585px;text-align:left;padding:10px;">
     <%=flash[:alerts] %>  
  </div>
 
<% end %> 
<div id="newsignupleftpanel" style="height : 350px">

<%= form_for :invitation, :url => get_invitation_token_invitations_url(@invitation.invitation_token), :html => {:method => :post, :id =>"user_new", :class => "user_new"} do |f| %>
<%= f.error_messages %>
<div class = "sub_header">Get Aothorized</div>
<ul class="formobj"  style="height : 350px;">
  <!--  <li>
	  <p>
	    <%= f.label :first_name %><br />
	    <%= f.text_field :first_name %>
	  </p>
    </li>
   
    <li> 
	  <p>
	    <%= f.label :last_name %><br />
	    <%= f.text_field :last_name %>
	  </p>
   </li>
   -->
    <li>
	  <p>
	    <%= f.label "enter email" %><br />
	    <%= f.text_field :recipient_email%>
	  </p>
    </li>
    <li></li>
    <li>
	  <p>
	    <%= f.label "enter authorize token"%><br />
	    <%= f.text_field :invitation_token%>
	  </p>
     </li>
</ul>
 <div class="other-info">
       <p class="btnbox" style="top:280px;">
	  <%= link_to "send invitaion", new_invitation_path%>
       </p>
       <div class="clear"></div>
     </div>


<p class="btnbox other-info" style="top:220px;"><input name="" type="submit" class="button" value="" align="absmiddle"/>
<!--<p class="btnbox other-info" style="top:220px;"><%= f.submit "Get Aothorized", :html => {:class => "button", :id =>"submit-signup", :align => "absmiddle"}%></p>-->

<% end %>
</div>
<div id="newsignuprightpanel">
 
   <img src="/images/vergin_add_img.jpg" />
  </div>
</div>
</div>

app/views/invitations/new.html.erb
<div id="toppanelbotmborder"></div>
<div id="newsignupmiddlepanel">
<div id="newsignupmiddlecontent">
 
<%= content_tag(:title, "Send Invitation") %>
  <% if @invitation.errors.any? %>  

   <div id="notification" style="width:585px;text-align:left;padding:10px;">
      <% @invitation.errors.full_messages.each do |msg| %>  
       <p><%= msg %></p>  
     <% end %>


     </div>


  
   <% end %>  

<% if notice %>
<div id="notification" style="width:900px;text-align:left">
    <p><%= notice.gsub("<br>","<br/>") %></p>
     </div>
<% end %>
<% if alert %>

<div id="notification" style="width:900px">
    <p><%= alert %></p>

     </div>
<% end %>

<div id="newsignupleftpanel" style="height : 400px;">
<%= form_for @invitation,  :html => {:method => :post, :id =>"user_new", :class => "user_new"} do |f| %>
<%#= f.error_messages %>
<div class="sub_header" >Send Invitation</div>
<ul class="formobj">
    <li>
	  <p>
	    <%= f.label :first_name %><br />
	    <%= f.text_field :first_name %>
	  </p>
    </li>
    <li></li>
    <li> 
	  <p>
	    <%= f.label :last_name %><br />
	    <%= f.text_field :last_name %>
	  </p>
   </li>
   <li></li>
    <li>
	  <p>
	    <%= f.label :recipient_email %><br />
	    <%= f.text_field :recipient_email%>
	  </p>
  </li>
</ul>
<div class="other-info">
       <p class="btnbox" style="top:340px;">
          <%#= link_to "Get Auothorized", authorize_invitations_path%>
       </p>
       <div class="clear"></div>
     </div>
<p class="btnbox other-info" style="top:280px;"><input name="" type="submit" class="button" value="" align="absmiddle"/>
<!--<p class="btnbox"><%#= f.submit "send invitation"%></p>-->

<% end %>
</div>
<div id="newsignuprightpanel">
 
   <img src="/images/vergin_add_img.jpg" />
  </div>
</div>
</div>