config/routes.rb
Millap::Application.routes.draw do

  controller :borrower do
    get 'borrower/new', :to => :new, :as => :new
    post 'borrower/create', :to => :create, :as => :create
  end

  controller :fieldpartner do
    get 'fp/new', :to => :new, :as => :new
    post 'fieldpartner/create', :to => :create, :as => :create
  end  

 devise_for :users, :path => "users", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'signup' }, :controllers => { :registrations => "registrations", :confirmations => :confirmations }

devise_for :users do
   get "/signup", :to => "registrations#new" # Add a Custom Route for Registrations
end

  root :to => "home#index"
 
  

  resources :invitations, :only => [:new, :create] do
     collection do
       get :authorize     
       post :get_invitation_token
       get :get_invitation_token
     end	    
   end

   
  controller :home do
    match 'about-milaap', :to => :about, :as => :about
    match 'how-it-works', :to => :how_it_work, :as => :how_it_work
    match 'get-involved', :to => :get_envolved, :as => :get_envolved
    match 'contact-us', :to => :contact_us, :as => :contact_us
    match 'advisory-board', :to => :advisory_board, :as => :advisory_board
    match 'team', :to => :team, :as => :team
    match 'volunteer', :to => :volunteer, :as => :volunteer
    match 'terms', :to => :terms, :as => :terms
    match 'jobs', :to => :jobs, :as => :jobs
    match 'privacy', :to => :privacy, :as => :privacy
    match 'view-all-projects', :to => :view_all_projects, :as => :view_all_projects
    match 'borrower-profile/:id/:name', :to => :borrower_profile, :as => :borrower_profile,:id=>/\d+/,:name=>/.*/
    match 'lender-profile', :to => :lender_profile, :as => :lender_profile
    match 'lend-money-to-borrower', :to => :lend_money_to_borrower, :as => :lend_money_to_borrower
    match 'who-we-are', :to => :who_we_are, :as => :who_we_are
    match 'verify-invitation-code', :to => :verify_invitation_code, :as => :verify_invitation_code
    match 'alpha', :to => :alpha_home, :as => :alpha_home
    match 'thanks', :to => :thank_you, :as => :thank_you
    match 'why-milaap', :to => :why_milaap, :as => :why_milaap
    match 'test', :to => :test, :as => :test
    match 'pledge-a-loan', :to => :pledge, :as => :pledge
    match 'edit-account', :to => :edit_user_account, :as => :edit_user_account
     match 'save-email-info', :to => :save_email_info, :as => :save_email_info
    get 'welcome', :to => :welcome, :as => :welcome
  end

 
  controller :paypal do
    get 'paypal-ipn', :to => :ipn, :as => :ipn
  end 

  controller :pay_tm do
    get 'paytm-ipn', :to => :ipn, :as => :ipn
  end

  controller :admin do
   match 'admin', :to => "Admin::Admin#index", :path => "Admin::Admin#index"
  end 

 controller :twitt_oauth do
    get 'twitter-login', :to => :twitter_login, :as => :twitter_login
    get 'twitter-callback', :to => :twitter_callback, :as => :twitter_callback
  end 

  controller :google_outh do
    get 'google-login', :to => :google_login, :as => :google_login
    get 'google-callback', :to => :google_callback, :as => :google_callback
  end 

 controller :facebook do
    get 'facebook-login', :to => :facebook_login, :as => :facebook_login
    get 'facebook-callback', :to => :facebook_call, :as => :facebook_call
  end

end

app/views/layouts/application-15-09 .html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>MILAAP - Beyond Just Credit</title>

<link rel="icon" href="/images/favicon.ico" type="image/x-icon" />
<%= stylesheet_link_tag "style.css" %>
<%= stylesheet_link_tag "slide.css" %>
<%= javascript_include_tag "slide.js" %>

</head>
<body>
<div id="toppanel">
  <div id="logopn"> <a href="/" title="MILAAP - Beyond Just Credit"><img src="/images/logo_img.jpg" alt="Milaap" width="221" height="104" align="left"/></a> </div>
  <ul class="menu">
    <li class="home"><a href="/" title="MILAAP - Beyond Just Credit"></a></li>
    <li class="about"><a href="<%= about_path %>" title="About MILAAP"></a></li>
    <li class="how"><a href="<%= how_it_work_path %>" title="MILAAP - How it works"></a></li>
    <li class="get"><a href="<%= get_envolved_path %>" title="Get involved with MILAAP"></a></li>
    <li class="blog"><a href="http://blog.milaap.org/" title="MILAAP - Beyond Just Credit"></a></li>
    <li class="contact"><a href="<%= contact_us_path %>" title="Contact MILAAP"></a></li>
  </ul>
  <% unless current_user.blank? %>
  <div class="welcome_msg"> <% unless current_user.facebook_uid.blank? %>
    <!--img src="https://graph.facebook.com/<%= current_user.facebook_uid %>/picture" align="left"/-->
  <% end %> Welcome,    <%if !current_user.facebook_name.blank? %><%= current_user.facebook_name %><% elsif !current_user.email.blank?%> <%= current_user.email[0..15] %><% else %>Ananymous<% end %><br/><a href="/users/logout">Logout</a> </div>

  <% else %>
  <div id="loginpanel">
    <ul class="loginmenu">
      <li class="join"><a id="login" href="#inline2"></a></li>
      <li class="sign"><a id="signup" href="#inline1"></a></li>
    </ul>
  </div>
  <% end %>
</div>
<% if user_signed_in? %>

<% else %>
<div style="display: none;">
  <!-- Login blurb-->
  <div id="inline1" style="width:500px;height:320px;overflow:hidden;">
    <form method="post" id="user_new" class="user_new" action="/users/login" accept-charset="UTF-8">
<div style="margin: 0pt; padding: 0pt; display: inline;"><input type="hidden" value="☃" name="_snowman"><input type="hidden" value="2wbLdqRz9PT5QmYT3AAaYo0Lv3NpczN+8UbNvM0oVnM=" name="authenticity_token"></div>    


  


      <div id="signup-new"> <img src="/images/signin_head_img.jpg" alt=""/>
        <div class="signup-left-panel">
          <h4>Sign in with your email</h4>
          <label>Email id</label>
          <input type="text" value=""   id="user_email" name="user[email]" class="input-text">
          <label>Password</label>
          <input type="password"  id="user_password" name="user[password]" class="input-text">
        </div>
        <div class="signup-right-panel">
          <h4>Sign in with another account</h4>
          <div style="display:block;">
           <%#= link_to "Login with facebook", user_fb_auth_path %>
           <a href="<%= user_fb_auth_path %>" > 
            <img class="left" src="/images/fb-connect.gif" alt="Facebook Connect" title="Sign in with facebook"/>
           </a>   
            <p class="left">Sign in with facebook</p>
            <p class="left">
              <%#= link_to "Sign in as User with Github", user_oauth_authorize_url(:github) %></p>

            <p class="clear"></p>
          </div>
          <div style="display:block; clear:both; padding-top:3px;"><a href="<%= url_for(user_session_path(:warden_oauth_provider => 'google')) %>"><img class="left" src="/images/Gmail_logo.png" alt="Twitter Connect" title="Sign in with Google"/></a>
            <p class="left">Sign in with Google</p>
          </div>
        </div>
        <div class="clear"></div>
        <div class="other-info"> <a href="/users/secret/new" class="left">Forgot password?</a><span style="padding:0 0 0 4px;" class="left">|</span>
          <p class="left"><a href="/users/register/signup" class="left" title="Sign up with Milaap">New User?  Signup Here</a>
          <%#= link_to 'Twitter Authentication', url_for(new_user_session_path(:warden_oauth_provider => :twitter))%>
           <%#= link_to 'Twitter Authentication', url_for(new_user_session_path(:warden_oauth_provider => :twitter))%>
            <%#= link_to("Login With Twitter", user_session_path(:warden_oauth_provider => 'twitter') ) %>

           <div class="clear"></div>
        </div>
        <div class="clear"></div>
        <input type="submit" value="" id="submit-signup">
      </div>
    </form>
  </div>
</div>

<div style="display: none;">
  <!-- Signup blurb-->
  <div id="inline2" style="width:500px;height:100%;overflow:hidden;">
    <form method="post" id="user_new" class="user_new" action="/users/register" accept-charset="UTF-8">
      <div style="margin: 0pt; padding: 0pt; display: inline;">
      <input type="hidden" value="☃" name="_snowman">
      <input type="hidden" value="2wbLdqRz9PT5QmYT3AAaYo0Lv3NpczN+8UbNvM0oVnM=" name="authenticity_token">
    </div>  
    

      <div id="login-new"> <img src="/images/signup_head_img.jpg" alt=""/>
        <div class="login-left-panel">
          <h4>Sign up with your email</h4>
          <label>Email id</label>
          <input type="text" name="user[email]"   id="user_email" class="input-text">
          <label>Password</label>
          <input type="password" name="user[password]"   id="user_password" class="input-text">
          <label>Password again</label>
          <input type="password" name="user[password_confirmation]"   id="user[password_confirmation]" class="input-text">
          <!--label>Username</label>
          <input type="text" name="user[username]"   id="user_username" class="input-text"-->
        </div>
        <div class="login-right-panel">
          <h4>Sign up with another account</h4>
          <div style="display:block;">  <a href="<%= user_fb_auth_path %>" > 
            <img class="left" src="/images/fb-connect.gif" alt="Facebook Connect" title="Sign up with facebook"/>
           </a> 
            <p class="left">Sign up with facebook</p>
            <p class="clear"></p>
          </div>
          <div style="display:block; clear:both; padding-top:3px;"><img class="left" src="/images/twitter-connect.png" alt="Facebook Connect"/>
            <p class="left">Sign up with Twitter</p>
          </div>
        </div>
        <div class="clear"></div>
        <div class="other-info"> <a href="">Already a user? Sign in here</a> </div>
        <div class="clear"></div>
        <input type="submit" id="submit-signin" value=""/>
      </div>
    </form>
  </div>
</div>
<!-- /Login blurb-->
<% end %>

<%= yield %>
<div id="footermainpanel">
  <div id="footerinnerpanel">
    <div id="footercontent1"> <img src="/images/why_choose_img.jpg" />
      <ul class="whyChoose">
        <li>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor </p>
        </li>
        <li>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor </p>
        </li>
        <li>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor </p>
        </li>
      </ul>
    </div>
    <div id="footercontent2"> <img src="/images/about_milap_img.jpg" />
      <ul class="aboutMilap">
        <li>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor </p>
        </li>
        <li class="advBoard"><a class="Advisory" href="<%= advisory_board_path %>" title="Advisory Board">Advisory Board</a> <span>|</span> <a class="Advisory" href="<%= team_path %>" title="Team">Team</a> <span>|</span> <a class="Advisory"  href="<%= volunteer_path %>" title="Volunteer">Volunteer </a></li>
        <li class="advBoard"><a class="Advisory" href="<%= terms_path %>" title="Terms">Terms</a> <span>|</span> <a class="Advisory" href="<%= privacy_path %>" title="Privacy">Privacy</a> <span>|</span> <a class="Advisory" href="<%= jobs_path %>" title="Jobs">Jobs</a> <span>|</span> <a class="Advisory" href="<%= contact_us_path %>" title="Contact">Contact </a></li>
      </ul>
    </div>
    <div id="footercontent3"> <img src="/images/our_partners_img.jpg" /> <img class="partners" src="/images/our_partners_product_img.jpg" /> </div>
  </div>
</div>
<div id="reserveid">
  <div id="reserveinner">
    <p>&copy; 2009 Milaap.org All Rights Reserved.</p>
  </div>
</div>
<script type="text/javascript">
$(function() {

  

        
    $('#slideshow').after('<div id="nav" class="nav">').cycle({
        fx:     'fade',
        speed:  'fast',
        timeout: 0,
        pager:  '#nav',
        before: onBefore
    });
    
        function onBefore() {
        $('#title').html(this.alt);
    }
});


$('#lend_id').click(function() {
  if($('#amount_id').value==''){
      alert("Please select device.");
      return false;
    }  

});


</script>
</body>
</html>

app/views/layouts/borrower.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>MILAAP - Beyond Just Credit</title>
<link rel="icon" href="/images/favicon.ico" type="image/x-icon" />

<%= stylesheet_link_tag "common.css" %>
<%= javascript_include_tag "jquery.js" %>
<%= javascript_include_tag "rails.js" %>
<%#= csrf_meta_tag %>


<!--[if lt IE 7]> <script type="text/javascript" src="js/unitpngfix.js"></script><![endif]-->
</head>

<body>
	<div id="header"><!-- Header div -->
	<div class="wrapper"><!-- Wrapper div -->
		<div id="logo" class="left"><a href="/"><img class="ie-png" src="/images/milaap.png"/></a></div>
		<div class="right">
			<div class="clear"></div>
			<ul id="primary-nav" style="display:block;"><!-- Primary nav div -->
				<li><a href="/" title="MILAAP - Beyond Just Credit" class="<% if  session[:tab] == 'home'%>active<% else%><% end %>">Home</a>
				</li>
				
				<% if user_signed_in? %>
				<%#= current_user.loan_pledged %>
	<% if current_user.loan_pledged == true %> 
	<li><a href="<%= view_all_projects_url %>" title="Give a loan" class="<% if  session[:tab] == 'pledge'%>active<% else%><% end %>">Give a loan</a></li>
	<% else %>
	<li><a href="<%= pledge_url %>" title="Pledge a loan" " class="<% if  session[:tab] == 'pledge'%>active<% else%><% end %>">Pledge a loan</a></li>
	<% end %>
	<% else %>
	<li><a href="<%= pledge_url %>" title="Pledge a loan" class="<% if  session[:tab] == 'pledge'%>active<% else%><% end %>">Pledge a loan</a></li>
	<% end %>
				  <li><a href="<%= why_milaap_path %>" title="MILAAP - Why Milaap" class="<% if  session[:tab] == 'why_milaap'%>active<% else%><% end %>">Why Milaap</a></li>
    <li><a href="<%= who_we_are_path %>" title="Who we are" class="<% if  session[:tab] == 'who_we_are'%>active<% else%><% end %>">Who we are</a></li>
    <li><a href="<%= how_it_work_path %>" title="MILAAP - How it works" class="<% if  session[:tab] == 'how_it_work'%>active<% else%><% end %>">How it works</a></li>
    <li><a href="<%= get_envolved_path %>" title="Get involved with MILAAP" class="<% if  session[:tab] == 'get_envolved'%>active<% else%><% end %>">Get involved</a></li>
				
				
				
				
				
			</ul><!-- /Primary nav div -->
		</div>
		<div class="clear"></div>
			
			<% unless current_user.blank? %>
			<ul id="member-status" style="display:block;">
				<li> <%if !current_user.facebook_name.blank? %>
      <img src="https://graph.facebook.com/<%= current_user.facebook_uid %>/picture" align="left" height="19px;" width="19px;"/>
 <span style="margin-left:5px;"><%= current_user.facebook_name %>
      <% elsif !current_user.email.blank?%>
      <%= current_user.email[0..15] %>
      <% elsif !current_user.twitter_name.blank?%>
      <%= current_user.twitter_name %>
      <% else %>
      Ananymous
      <% end %></span></li> | 
				<li><a href="/users/logout">Logout</a></li>
				<li><a href="" class="clear"></a></li>
			</ul>
			
		  <% end %>	
		</div><!-- /Wrapper div -->

	</div><!-- /Header div -->
	
		<%= yield %>
	
	<div id="footer"  style="margin-top:0px;"><!-- Footer div -->
		<div class="wrapper">
			<ul class="left">
			  <li><a title="Privacy Policy" href="/privacy">Privacy Policy</a></li> | <li><a title="Terms and Conditions" href="/terms">Terms &amp; Conditions</a></li> | <li><a title="MILAAP - Beyond Just Credit" href="http://blog.milaap.org/">Blog</a></li> | <li><a title="Contact Milaap" href="/contact-us">Contact Us</a></li>
			</ul>
			<div class="copyright right">
			  <p>&copy; 2010. Milaap.org. All rights reserved.</p>
			</div>
			<div class="clear"></div>
		</div><!-- /Wrapper div -->
	</div><!-- /Footer div -->

<script type="text/javascript">
 $(".accordion h4").click(function(){
        $(this).next("p").toggle("slow")
        $(this).toggleClass("active");
             
        });


$("#choose-amount input").hover(
  function () {
    $(this).addClass("btnhover");
  },
  function () {
    $(this).removeClass("btnhover");
  }
);
setTimeout(fade_out, 10000);
function fade_out() {
  $("#notification").fadeOut().empty();
}

</script>


     <script type="text/javascript">
    	var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    	document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
    	</script>
    	<script type="text/javascript">
    	var pageTracker = _gat._getTracker("UA-4054156-1");
    	pageTracker._setDomainName("none");
    	pageTracker._setAllowLinker(true);
    	pageTracker._setAllowHash(false);
    	pageTracker._initData();
    	pageTracker._trackPageview();
    	</script>  

</body>
</html>

app/views/layouts/old_application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>MILAAP - Beyond Just Credit</title>
<link rel="icon" href="/images/favicon.ico" type="image/x-icon" />

<%= stylesheet_link_tag "style.css" %>
<%= stylesheet_link_tag "slide.css" %>
<%#= javascript_include_tag :defaults %>
<%= javascript_include_tag "jquery-1.3.2.min.js" %>
<%= javascript_include_tag "jquery.cycle.all.min.js" %>
<%= javascript_include_tag "slide.js" %>
<%= csrf_meta_tag %>

</head>

<body>
<div id="toppanel">
  <div id="logopn"> <a href="/" title="MILAAP - Beyond Just Credit"><img src="/images/logo_img.jpg" alt="POWERTRONIKS" width="221" height="104" align="left"/></a> </div>
  <ul class="menu">
    <li class="home"><a href="/" title="MILAAP - Beyond Just Credit"></a></li>
    <li class="about"><a href="<%= about_path %>" title="About MILAAP"></a></li>
    <li class="how"><a href="<%= how_it_work_path %>" title="MILAAP - How it works"></a></li>
    <li class="get"><a href="<%= get_envolved_path %>" title="Get involved with MILAAP"></a></li>
    <li class="blog"><a href="http://blog.milaap.org/" title="MILAAP - Beyond Just Credit"></a></li>
    <li class="contact"><a href="<%= contact_us_path %>" title="Contact MILAAP"></a></li>
  </ul>
 <% unless current_user.blank? %> 
  <div>
      Welcome, <%= current_user.username %> | <a href="/users/logout">Logout</a>
  </div>

<% else %>
 <div id="loginpanel">
    <ul class="loginmenu">
      <li class="join"><a href="#" id="signup_id"></a></li>
      <li class="sign"><a href="#" id="login_id"></a></li>
    </ul>
  </div>
<% end %>


</div>

<div id="bannerpanel">
  <div id="bannermiidlepanel">
    <div id="bannerleftpanel">
      <h2>Open a school in Nasik</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore</p>
      <p class="more"><a href="#">more</a></p>
    </div>
    <div id="bannerrightpanel">
      <div id="demo">
        <div id="slideshow" class="pics"> <img src="images/banner_right_inner.jpg" /> <img src="images/banner_right_inner.jpg" /> <img src="images/banner_right_inner.jpg" /> <img src="images/banner_right_inner.jpg" /> </div>
      </div>
    </div>
  </div>
</div>


<%= yield%>




<div id="footermainpanel">
	<div id="footerinnerpanel">
		<div id="footercontent1">
			<img src="/images/why_choose_img.jpg" />
			<ul class="whyChoose">
				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor </p></li>
				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor </p></li>
				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor </p></li>
			</ul>
	  </div>
	  <div id="footercontent2">
			<img src="/images/about_milap_img.jpg" />
			<ul class="aboutMilap">
				<li><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor </p></li>
				<li class="advBoard"><a class="Advisory" href="<%= advisory_board_path %>" title="Advisory Board">Advisory Board</a> <span>|</span> <a class="Advisory" href="<%= team_path %>" title="Team">Team</a> <span>|</span> <a class="Advisory"  href="<%= volunteer_path %>" title="Volunteer">Volunteer </a></li>
				<li class="advBoard"><a class="Advisory" href="<%= terms_path %>" title="Terms">Terms</a> <span>|</span> <a class="Advisory" href="<%= privacy_path %>" title="Privacy">Privacy</a> <span>|</span> <a class="Advisory" href="<%= jobs_path %>" title="Jobs">Jobs</a> <span>|</span> <a class="Advisory" href="<%= contact_us_path %>" title="Contact">Contact </a></li>
			</ul>
	  </div>
	  <div id="footercontent3">
			<img src="/images/our_partners_img.jpg" />
			<img class="partners" src="/images/our_partners_product_img.jpg" />
	  </div>
	</div>
</div>
<div id="reserveid">	
	<div id="reserveinner">
	<p>&copy; 2010 Milaap.org All Rights Reserved.</p>
	</div>
</div>


<div class="fade1" style="display:none" id="login_fade_id">&nbsp;</div>

<div class="popup1_big" id="pop_up_box_login_id" style="display:none;">
        <div style="height:12px"><img src="/images/light_box_top.png"/></div>
        <div class="popup1_block_big"><img src="/images/icon_close.png"  class="cntrl" border="none" onclick="" style="cursor:pointer" title="Close" id="close_pop_up_id"/>
          <div style="overflow:hidden;" class="">
            <div style="overflow:hidden; width:350px;padding:10px; padding-left:20px">
              <h3 style="font-family:Arial,Verdana;font-size:14pt;font-weight:bold;letter-spacing:-1px;margin:0 0 0;padding:0;">Log into Milaap</h3>
              <br/>
              <div id="update_login_id">
        <form method="post" id="user_new" class="user_new" action="/users/login" accept-charset="UTF-8" data-remote="true"><div style="margin: 0pt; padding: 0pt; display: inline;"><input type="hidden" value="☃" name="_snowman"><input type="hidden" value="s0rOQTEvumSKKqR8cLC/M01N84KrPJzXHPYOaVrCtLg=" name="authenticity_token"></div>
  <p class="conntent_new"><label for="user_email">Email</label> : <input type="text" value=""   id="user_email" name="user[email]" class="login_textbox"></p>

  <p class="conntent_new"><label for="user_password">Password</label> : <input type="password"  id="user_password" name="user[password]" class="login_textbox"></p>

    <!--p><input type="hidden" value="0" name="user[remember_me]"><input type="checkbox" value="1" name="user[remember_me]" id="user_remember_me"> <label for="user_remember_me">Remember me</label></p-->

  <p><input type="submit" value="Sign in" name="commit" id="user_submit"></p>
</form>
              
             
      


          

            </div>
            </div>
          </div>
        </div>
        <div><img src="/images/light_box_bot.png"/></div>
      </div>

<div class="fade1" style="display:none" id="sign_up_fade_id">&nbsp;</div>


<div class="popup1_big" id="pop_up_box_sign_up_id" style="display:none;">
        <div style="height:12px"><img src="/images/light_box_top.png"/></div>
        <div class="popup1_block_big"><img src="/images/icon_close.png"  class="cntrl" border="none" id="close_signup_pop_up_id" style="cursor:pointer" title="Close"/>
          <div style="overflow:hidden;" class="">
            <div style="overflow:hidden; width:350px;padding:10px; padding-left:20px">
              <h3 style="font-family:Arial,Verdana;font-size:14pt;font-weight:bold;letter-spacing:-1px;margin:0 0 0;padding:0;">Join Milaap</h3>
              <br/>
              <div id="update_signup_id">
               <form method="post" id="user_new" class="user_new" action="/users/register" accept-charset="UTF-8"><div style="margin: 0pt; padding: 0pt; display: inline;"><input type="hidden" value="☃" name="_snowman"><input type="hidden" value="7W415AM9Jwrge/c5Ml5WqJn/2R8pvlXrjZuKnomBDNM=" name="authenticity_token"></div>
   

<p class="conntent_new"><label for="user_email">Email</label> : <input type="text" name="user[email]"   id="user_email" class="login_textbox"></p>

   <p class="conntent_new"><label for="user_password"></label> Password: <input type="password" name="user[password]"   id="user_password" class="login_textbox">
   </p>


   <p class="conntent_new"><label for="user_password_confirmation">Confirm Password</label> : <input type="text" name="user[password_confirmation]"   id="user[password_confirmation]" class="login_textbox">
   </p>


   <p class="conntent_new"><label for="user_first_name">First Name</label> : <input type="text" name="user[first_name]"   id="user_first_name" class="login_textbox">
   </p>

    <p class="conntent_new"><label for="user_last_name">Last Name</label> : <input type="text" name="user[last_name]"   id="user_last_name" class="login_textbox">
   </p>

   <p class="conntent_new"><label for="user_username">Username</label> : <input type="text" name="user[username]"   id="user_username" class="login_textbox">
   </p>






  <p><input type="submit" value="Sign up" name="commit" id="user_submit"></p>
</form>


              </div>
            </div>
          </div>
        </div>
        <div><img src="/images/light_box_bot.png"/></div>
      </div>








<script type="text/javascript">
$(function() {
        
    $('#slideshow').after('<div id="nav" class="nav">').cycle({
        fx:     'fade',
        speed:  'fast',
        timeout: 0,
        pager:  '#nav',
        before: onBefore
    });
    
        function onBefore() {
        $('#title').html(this.alt);
    }
});
$('#login_id').click(function() {
$('#login_fade_id').show();
$('#pop_up_box_login_id').show();
});


$('#close_pop_up_id').click(function() {
$('#login_fade_id').hide();
$('#pop_up_box_login_id').hide();
});


$('#signup_id').click(function() {
$('#sign_up_fade_id').show();
$('#pop_up_box_sign_up_id').show();
});


$('#close_signup_pop_up_id').click(function() {
$('#sign_up_fade_id').hide();
$('#pop_up_box_sign_up_id').hide();
});








</script>
</body>
</html>